version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - "> 5.35.0, < 5.36"
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.16
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
    - 16.5.3
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: html-loader
    versions:
    - 1.3.2
  - dependency-name: terser-webpack-plugin
    versions:
    - 4.2.3
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: mini-css-extract-plugin
    versions:
    - 0.9.0
  - dependency-name: sass-loader
    versions:
    - 7.3.1
  - dependency-name: eslint
    versions:
    - 6.8.0
  - dependency-name: concurrently
    versions:
    - 5.1.0
